config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get '/dashboard', to: 'pages#dashboard', as: :dashboard
  get '/invoices', to: 'pages#invoices', as: :invoices
  get '/payments', to: 'pages#payments', as: :payments

  resources :profiles, only: [:index, :new, :create, :destroy, :update]
  resources :transactions, only: [:create, :destroy]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_many :transactions, dependent: :destroy
  belongs_to :user
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :profile
  validates :amount, presence: true
  validates :company_paid, presence: true
  validates :nature, inclusion: { in: %w[invoice payment],
                                message: 'Please choose "invoice" or "payment"' }
  validate :transaction_date_cannot_be_in_the_future
  validates :description, length: { maximum: 500 }

  def transaction_date_cannot_be_in_the_future
    if date.present? && date > Date.today
      errors.add(:date, "can't be in the future")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :profiles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  include Pundit
  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def after_sign_in_path_for(user)
    if user.profiles.empty?
      new_profile_path
    else
      dashboard_path
    end
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    session[:profile_id] = nil
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]
  before_action :set_active_profile, only: [:dashboard, :invoices, :payments]

  def home
    @page = "home"
  end

  def dashboard
    @page = "dashboard"
    authorize @active_profile, policy_class: ProfilePolicy
    # Retrieve invoices and payments
    @invoices = Transaction.where(profile: @active_profile, nature: "invoice")
    @payments = Transaction.where(profile: @active_profile, nature: "payment")

    # Calculate daily, monthly and balance totals
    @credit_day = calc_total_today("invoice")
    @debit_day = calc_total_today("payment")
    @credit_month = calc_total_month("invoice")
    @debit_month = calc_total_month("payment")
    @balance = calc_balance

    # Initiate a new invoice for the invoice form
    @new_invoice = Transaction.new
    @new_invoice.nature = "invoice"
    @new_invoice.profile_id = @active_profile.id

    # Initiate a new payment for the payment form
    @new_payment = Transaction.new
    @new_payment.nature = "payment"
    @new_payment.profile_id = @active_profile.id
  end

  def invoices
    @page = "invoices"
    authorize @active_profile, policy_class: ProfilePolicy
    # Retrieve invoices, sort them by date descending and limit the answer size
    @invoices = Transaction.where(profile: @active_profile, nature: "invoice").order("created_at DESC").limit(30)
    # Initiate a new invoice for the invoice form
    @new_invoice = Transaction.new
    @new_invoice.nature = "invoice"
    @new_invoice.profile_id = @active_profile.id
  end

  def payments
    @page = "payments"
    authorize @active_profile, policy_class: ProfilePolicy
    # Retrieve invoices
    @payments = Transaction.where(profile: @active_profile, nature: "payment").order("created_at DESC").limit(30)
    # Initiate a new payment for the payment form
    @new_payment = Transaction.new
    @new_payment.nature = "payment"
    @new_payment.profile_id = @active_profile.id
  end

  private

  # DASHBOARD CALCULATIONS
  def calc_total_today(nature)
    # nature should be equal to "invoice" or "payment"
    transactions = Transaction.where(profile: @active_profile, nature: nature, date: Date.today.all_day)
    transactions.reduce(0) { |total, transaction| total + transaction.amount }
  end

  def calc_total_month(nature)
    # nature should be equal to "invoice" or "payment"
    month = Date.today.month
    transactions = Transaction.where(profile: @active_profile, nature: nature)
                              .where("EXTRACT(MONTH FROM date) = ?", month)
    transactions.reduce(0) { |total, transaction| total + transaction.amount }
  end

  def calc_total(nature)
    # nature should be equal to "invoice" or "payment"
    transactions = Transaction.where(profile: @active_profile, nature: nature)
    transactions.reduce(0) { |total, transaction| total + transaction.amount }
  end

  def calc_balance
    # nature should be equal to "invoice" or "payment"
    tot_invoice = calc_total("invoice")
    tot_payment = calc_total("payment")
    return tot_invoice - tot_payment
  end

  def set_active_profile
    # Get every profile of the user
    if params[:profile_id]
      session[:profile_id] = params[:profile_id]
      # If a param is setting the profile_id used than set it as active_profile
      @active_profile = Profile.find(session[:profile_id])
    elsif session[:profile_id]
      @active_profile = Profile.find(session[:profile_id])
    else
      # Set the profile as the first of the user
      @profiles = current_user.profiles
      @active_profile = @profiles.first
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[destroy update]

  def index
    @profiles = policy_scope(Profile)
  end

  def new
    @profile = Profile.new
    authorize @profile
  end

  def create
    @profile = Profile.new(profile_params)
    authorize @profile
    @profile.user = current_user
    if @profile.save
      redirect_to dashboard_path(profile_id: @profile.id)
    else
      render 'new'
    end
  end

  def show
  end

  def destroy
    authorize @profile
    @profile.destroy
    redirect_to profiles_path
  end

  def update
    raise
    @profile.color = profile_params.color
  end

  private

  # USUAL HELPERS
  def profile_params
    params.require(:profile).permit(:name, :color)
  end

  def set_profile
    @profile = Profile.find(params[:id])
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  def create
    @transaction = true
    @page = params[:transaction][:page]
    case params[:transaction][:nature]
    when "payment"
      @new_payment = Transaction.new(payment_params)
      authorize @new_payment
      if @new_payment.save
        redirect_to redirection_url(@page)
      else
        render "_payment_form", new_payment: @new_payment
      end
    when "invoice"
      @new_invoice = Transaction.new(invoice_params)
      @new_invoice.company_paid = "N/A"
      authorize @new_invoice
      if @new_invoice.save
        redirect_to redirection_url(@page)
      else
        render "_invoice_form", new_invoice: @new_invoice
      end
    else
      render './pages/dashboard'
    end
  end

  def destroy
    @id = params[:id]
    @transaction = Transaction.find(@id)
    authorize @transaction
    @transaction.destroy
    case @transaction.nature
    when "invoice"
      redirect_to invoices_path
    when "payment"
      redirect_to payments_path
    else
      redirect_to :root
    end
  end

  private

  def invoice_params
    params.require(:transaction).permit(:amount, :nature, :date, :profile_id, :received)
  end

  def payment_params
    params.require(:transaction).permit(:amount, :nature, :date, :company_paid, :profile_id, :description)
  end

  def redirection_url(origin)
    case origin
    when "dashboard"
      return dashboard_path
    when "invoices"
      return invoices_path
    when "payments"
      return payments_path
    else
      dashboard_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>B2BPaymentManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>


  <% unless current_user.nil? || @page == "home" %>
    <%= render 'shared/navbar' %>
  <% end %>
    <%= render 'shared/flashes' %>
  <% if @transaction %>
    <div class="main" style="padding: 5rem; overflow:hidden;">
      <%= yield %>
    </div>
  <% else %>
    <%= yield %>
  <% end %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div id="dashboard" class="main">
  <div class="annual bg-white rounded">
    <h1>Dashboard - <%= @active_profile.name %></h1>
  </div>
  <div class="forms">
    <%= render  "transactions/invoice_form", new_invoice: @new_invoice, page: @page %>

    <%= render  "transactions/payment_form", new_payment: @new_payment, page: @page%>
    </div>
  <div class="calcs">
    <div class="calc-card">
      <h3>Balance</h3>
      <% unless @invoices.empty? && @payments.empty? %>
        <p class="number-bg">$<%= @balance %></p>
      <% end %>
    </div>
    <div class="calc-card">
      <% unless @credit_day.nil? %>
        <h3>Today</h3>
        <div class="sold-line">
          <p class="number-md">$<%= @credit_day %></p>
          <p>Credit</p>
        </div>
        <div class="sold-line">
          <p class="number-md">$<%= @debit_day %></p>
          <p>Debit</p>
        </div>
      <% end %>
    </div>
    <div class="calc-card">
      <% unless @credit_month.nil? %>
        <h3>Current month</h3>
        <div class="sold-line">
          <p class="number-md">$<%= @credit_month %></p>
          <p>Credit</p>
        </div>
        <div class="sold-line">
          <p class="number-md">$<%= @debit_month %></p>
          <p>Debit</p>
        </div>
      <% end %>
    </div>
  </div>

</div>

app/views/pages/home.html.erb
<div id="home">
  <div class="section-title bg-white rounded text-center">
    <h1>Welcome to Beatle</h1>
    <br>
    <p>Manager your finances in a simple and understandable way</p>
  </div>
  <div class="section-devise bg-white rounded text-center">
    <div class="devise-content">
      <p>If you already have an account please log in <br>
      otherwise click on the sign in button</p>
      <div class="button-wrapper d-flex justify-content-around mt-5">
        <%= link_to  "LOGIN", new_user_session_path, class:"btn btn-outline-primary" %>
        <%= link_to  "SIGN UP",  new_user_registration_path, class:"btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/pages/invoices.html.erb
<div id="invoices" class="main">
  <div class="tb bg-white rounded p-3 m-3">
    <div class="table-title">
      <h1><%= @active_profile.name %></h1>
    </div>
    <div class="tb-content-titles">
      <label>Received</label>
      <label>Due Date</label>
      <label>Amount (in $)</label>
      <label></label>
    </div>
    <div class="table-content">
      <% @invoices.each do |invoice| %>
        <div class="tb-content-line">
          <% if invoice.received %>
            <div class="tb-content-line-item">
              <div class="circle green"></div>
            </div>
          <% else %>
            <div class="tb-content-line-item">
              <div class="circle red"></div>
            </div>
          <% end %>
          <span class="tb-content-line-item"><%= invoice.date %></span>
          <span class="tb-content-line-item"><%= invoice.amount %></span>
          <%= link_to transaction_path(invoice), method: :delete, data:{ confirm: "Are you sure you want to delete this transaction?"}, class:"tb-content-line-item" do%>
            <i class="fa fa-trash" aria-hidden="true"></i>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <%= render  "transactions/invoice_form", new_invoice: @new_invoice, page: @page %>
</div>

app/views/pages/payments.html.erb
<div id="payments" class="main">
  <div class="tb bg-white rounded p-3 m-3">
    <div class="table-title">
      <h1><%= @active_profile.name %></h1>
    </div>
    <div class="tb-content-titles">
      <label>Company paid</label>
      <label>Date</label>
      <label>Amount (in $)</label>
      <label></label>
    </div>
    <div class="table-content">
      <% @payments.each do |payment| %>
        <div class="tb-content-line">
          <span class="tb-content-line-item"><%= payment.company_paid %></span>
          <span class="tb-content-line-item"><%= payment.date %></span>
          <span class="tb-content-line-item"><%= payment.amount %></span>
          <%= link_to transaction_path(payment), method: :delete, data:{ confirm: "Are you sure you want to delete this transaction?"}, class:"tb-content-line-item" do%>
            <i class="fa fa-trash" aria-hidden="true"></i>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <%= render  "transactions/payment_form", new_payment: @new_payment, page: @page %>
</div>

app/views/profiles/edit.html.erb
<h1>Profiles#edit</h1>
<p>Find me in app/views/profiles/edit.html.erb</p>

app/views/profiles/index.html.erb
<div class="main" style="padding: 5rem; overflow:hidden;">
  <div class="cards d-flex">
    <% @profiles.each do |profile| %>
      <div class="card m-3" style="width: 18rem;">
        <div class="card-body align-items-center d-flex flex-column">
          <div class="circle-lg"></div>
          <h5 class="card-title mt-3"><%= profile.name %></h5>
          <%= link_to  "Pick: " + profile.name, dashboard_path(profile_id: profile.id), class:"btn" %>
          <%= link_to profile_path(profile), method: :delete, data:{ confirm: "Are you sure you want to delete this profile?"}, class:"delete-profile" do %>
            <i class="fa fa-trash" aria-hidden="true"></i>
          <% end %>
        </div>
      </div>
    <% end %>
    <div class="card-body align-items-center justify-content-center d-flex flex-column">
      <%= link_to  "Create a new profile", new_profile_path, class:"btn" %>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="main">
  <%= simple_form_for @profile do |f| %>
    <%= f.input :name, label: "Enter your company's name" %>
    <%= f.submit 'Create', class:"btn" %>
  <% end %>
</div>

app/views/profiles/show.html.erb
<h1>Profiles#show</h1>
<p>Find me in app/views/profiles/show.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
  <nav class="nav">

    <%= cl_image_tag "nav-button-gray_k13plb.png", id:"nav-btn-gray", class:"nav__expand hide" %>
    <div id="circle-gray" class="circle bg-blue nav__expand hide"></div>
    <%= cl_image_tag "nav-button-white_xisash.png", id:"nav-btn-white", class:"nav__expand" %>
    <div id="circle-white" class="circle bg-blue nav__expand"></div>
    <ul class="nav__list">
      <li class="nav__listitem pl-1 d-flex align-items-center">
          <div class="color-picker"></div>
          <p class="m-0 pl-2">Change color</p>
      </li>
      <li class="nav__listitem <%= "nav__listitem-active" if @page == 'dashboard' %>">
        <%= link_to dashboard_path, id:"dashboard-icon" do %>
          <p>Dashboard</p>
        <% end %>
      </li>
      <li class="nav__listitem <%= "nav__listitem-active" if @page == 'payments' %>">
        <%= link_to  payments_path, id:"payments-icon" do %>
          <p>Payments</p>
        <% end %>
      </li>
      <li id="pri-menu-end" class="nav__listitem  <%= "nav__listitem-active" if @page == 'invoices' %>">
        <%= link_to  invoices_path, id:"invoices-icon" do %>
          <p>Invoices</p>
        <% end %>
      </li>
      <li class="nav__listitem <%= "nav__listitem-active" if @page == 'settings' %>">
        <%= link_to  profiles_path, id:"settings-icon" do %>
          <p>Profiles</p>
        <% end %>
      </li>
      <li class="nav__listitem">
        <%= link_to  destroy_user_session_path, method: :delete, id:"logout-icon" do %>
          <p>Log Out</p>
        <% end %>
      </li>
    </ul>
  </nav>

app/views/transactions/_invoice_form.html.erb
<%= simple_form_for @new_invoice do |f| %>
  <div class="form-title">
    <h3>New invoice</h3>
    <%= f.submit "Create Invoice", class:"btn btn-outline-primary"%>
  </div>
  <%= f.input :amount, label: "Amount" %>
  <%= f.input :date, label: "Due date" %>
  <%= f.input :received, label: "Status" %>
  <%= f.hidden_field :nature, value: @new_invoice.nature %>
  <%= f.hidden_field :profile_id, value: @new_invoice.profile_id %>
  <%= f.hidden_field :page, value: @page %>
<% end %>

app/views/transactions/_payment_form.html.erb
<%= simple_form_for @new_payment do |f| %>
  <div class="form-title">
    <h3>New payment</h3>
    <%= f.submit "Create Payment", class:"btn btn-outline-primary"%>
  </div>
  <%= f.input :amount, label: "Amount" %>
  <%= f.input :date, label: "Date" %>
  <%= f.input :company_paid, label: "Company" %>
  <%= f.input :description, label: "Description" %>
  <%= f.hidden_field :nature, value: @new_payment.nature %>
  <%= f.hidden_field :profile_id, value: @new_payment.profile_id %>
  <%= f.hidden_field :page, value: @page %>
<% end %>